server:
  port: 8000

spring:
  application:
    name: exchange-service

  datasource:
    url: jdbc:postgresql://localhost:5432/excahnge_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false