CREATE TABLE exchange (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_currency CHAR(3) NOT NULL,
    to_currency CHAR(3) NOT NULL,
    conversion_factor NUMERIC(65,2) NOT NULL,

    CONSTRAINT uk_exchange_currency
        UNIQUE (from_currency, to_currency)
);